name: Push Github Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch the theme and its submodules
          fetch-depth: 1  # the dependency of the themes have very long histories

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm install

      - name: Install docsy dependencies
        run: cd themes/docsy && npm install

      - name: Build
        run: npm run build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Clone OSRD repository
        run: git clone https://github.com/DGEXSolutions/osrd.git /tmp/osrd_repo

      - name: Load cached venv
        uses: actions/cache@v3
        id: cached-poetry-dependencies
        with:
          path: /tmp/osrd_repo/python/api/.venv
          key: osrd-api-venv-${{ hashFiles('/tmp/osrd_repo/api/poetry.lock') }}

      - name: Install dependencies
        run: |
          cd /tmp/osrd_repo/python/api
          poetry install --no-interaction --no-root -E production

      - name: Add JSON schemas
        env:
          OSRD_DEV: "True"
        run: |
          source /tmp/osrd_repo/python/api/.venv/bin/activate
          mkdir -p public/schemas
          python /tmp/osrd_repo/python/api/manage.py json_schema infra > public/schemas/infra_schema.json
          python /tmp/osrd_repo/python/api/manage.py json_schema rolling_stock > public/schemas/rolling_stock_schema.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: osrd.fr
